// The emails table is defined with a one email to many recipients. In the
// situation that there are many recipients, the recipients are stored a seperate table.
// For simplicity, the recipients could be stored on this (emails) table as a long text string.

Table emails {
    email_id integer [pk, increment]
    body text
    subject varchar(256)
    email_date date [not null, default: now()]
    senderMailbox varchar(256) [not null]
}

// Needed stored procedures

// insertEmail that accepts a body, subject, and sender.

Table recipients {
    recipient_id integer [pk, increment]
    email_id integer [ref: < emails.email_id]
    email_address varchar(256) [not null]
    send_date date [not null, default: now()]
}

// Needed stored procedures

// insertRecipient that accepts an email_id, the receiver's email_address, and the send_date.